### ISSUE TITLE
Ukol 1 mam hotovy

### ISSUE THREAD

**Issue by LenkaLoukotova** [LenkaLoukotova/Python-for-Data-Science-2023#1]
@AnetaPopelova Dekuju za opravu a rady :)

**Comment by pesikj** [comment]
Ahoj @LenkaLoukotova,

omlouvám se za zpoždění, s Anet jsme si to vyměnili :-) Úkol je zpracovaný moc hezky. Hrozně se mi líbí, že jsi na výběr největšího rozdílu použila sort_values() a head(). To je podle mě úplně nejlepší řešení, protože je snadné si pak zobrazit třeba 3 nebo 5 nejvíce podhodnocených. To je super :-)

Jirka

**Comment by LenkaLoukotova** [comment]
Ahoj @pesikj ,

moc děkuju za opravu a zpětnou vazbu! :-)

Lenka
